# Generated by Django 4.1.5 on 2023-02-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=50),
        ),
    ]
